### ISSUE TITLE
基本が二段組のフォーマットに対して一段組で図を貼りたい

### ISSUE THREAD

**Issue by ebihara302** [taiga4112/jasnaoe_template_typst#13]
やったこと

= 二段組の文書
この部分は二段組です。テキストが続きます。二段組のレイアウトが適用されています。
#columns(1)
 = 一段組のセクション
この部分は一段組です。テキストが続きます。ここでは一段組のレイアウトが適用されています。
 #columns(2)
= また二段組
この部分は再び二段組です。二段組のレイアウトに戻っています。
これでいける？？

 main.styに対して
`#columns(1)
#figure(
  placement: none,
  image("figs/Proposed_TPG_ship_design_operation.png", width: 100%),
  caption: [Proposed TPG ship design operation.],
) <fig:Proposed_TPG_ship_design_operation>
#columns(2)`
とやると1行目でmissing argument: bodyとエラーが出てしまい図の状態から変化ありませんでした。chatGPTに投げてみたら以下のように書く必要があると出てきました。
`#columns(1)[
  #figure(
  placement: none,
  image("figs/Proposed_TPG_ship_design_operation.png", width: 100%),
  caption: [Proposed TPG ship design operation.],
) <fig:Proposed_TPG_ship_design_operation>
]
#columns(2)[]`
上記エラーは発生しませんでしたが、少なくとも私の環境では実現できませんでした。

**Comment by taiga4112** [comment]
[これ](https://www.reddit.com/r/typst/comments/1bcfysz/figure_across_multiple_columns/)を見ると、現時点では対応不可で、typst v0.12以降で再チェックかなと

**Comment by hinata235** [comment]
この件に関するTypstの[issue](https://github.com/typst/typst/issues/553)を見つけました。

**Comment by taiga4112** [comment]
これ、結局根本は解決していないんですよね・・・

**Comment by taiga4112** [comment]
Typst v0.12で解決しました。
https://typst.app/docs/reference/model/figure/

事前に、`set page(columns: 2)`という設定をしている前提ですが
`scope`という属性で`parent`とすると1段組みの図になります。
ただし、`placement`が`none`だと駄目みたいです。そこも含めて良い仕組みだと思います。

```typst
#figure(
  placement: bottom, // top, bottom, auto, none
  image("figs/example.svg", width: 100%),
  scope: "parent",
  caption: [Example of a figure.],
) <fig:fig_example>
```
