### ISSUE TITLE
参考文献リストを直書きでなくbibファイルやyamlファイルを読み込んで自動的に表示させたい

### ISSUE THREAD

**Issue by taiga4112** [taiga4112/jasnaoe_template_typst#15]
Typstには良い感じの[bibliography機能](https://typst.app/docs/reference/model/bibliography/)がある。これを使えないか。
直書きはいかにもミスが多くなる＆引用忘れが発生しそう。

**Comment by taiga4112** [comment]
対応するために、試しにCSLファイルを作ってみたのが[こちら](https://gist.github.com/taiga4112/2742added509b20082fa7d455f4df371)。

一方で、
- JASNAOE独自フォーマットがつらい（これはまぁ頑張ればなんとかなる）
- 日本語論文は英日併記というのがもはや厳しい

という理由で、現時点では断念。

独自フォーマットはこちら
![スクリーンショット 2024-08-19 12 11 41](https://github.com/user-attachments/assets/862a316a-c5a2-428f-a207-045ea084787c)

**Comment by taiga4112** [comment]
誰か熱意のある人はトライしてみてくださいませ（断念宣言）

**Comment by YasuoIchinose** [comment]
日本語との併記は難しそうだが、いい [Visual Editor](https://editor.citationstyles.org/visualEditor/)を見つけたので、編集してみた。

```
3) Campbell, J. L. & Pedersen, O. K. : The varieties of capitalism and hybrid success, Comparative Political Studies, 40, 307–332, 2007.
```

**Comment by taiga4112** [comment]
先ほどJASNAOEに確認したら、

> 日本語論文は英日併記

は間違いで

> 日本語論文のうち正式な英訳があれば英語のみの表記でOK

らしいです。

**Comment by taiga4112** [comment]
@y0o0ic 参考文献、「＆」ではなく「and」にするべき部分があるのですが、
CSL側で対応可能ですか？これができたら、こちらを正としてmainブランチにマージします。

公式テンプレート
<img width="412" alt="スクリーンショット 2024-09-12 14 31 42" src="https://github.com/user-attachments/assets/c46cc72f-a7ba-483a-a560-0e05296a8b74">

現時点でのCSLを使った参考文献
<img width="459" alt="スクリーンショット 2024-09-12 14 31 57" src="https://github.com/user-attachments/assets/2cfbbc86-aa2d-489a-8d9b-99579be613b1">
