### ISSUE TITLE
章のタイトルがボールドになっていない

### ISSUE THREAD

**Issue by YasuoIchinose** [taiga4112/jasnaoe_template_typst#17]
章のタイトルがボールドになるようにしたい。
（海技研の中で指摘され却下されてしまった。）

---
**現状のTypst**
![タイトルTypst](https://github.com/user-attachments/assets/856a1465-3756-4819-8aa6-f9a689f61c56)

---
**学会Word例**
![タイトル例](https://github.com/user-attachments/assets/d7e16d8a-38cb-4127-b203-64a74fa149eb)

**Comment by taiga4112** [comment]
ぐぬぬ。後で（今日の夕方？）修正チャレンジします。

**Comment by taiga4112** [comment]
@y0o0ic 私のノートPC(MacBook)での簡単な調査結果、Typstの設定はしっかりできているが、
採用している日本語フォントがIPAexGothicのため、ボールドに設定しても見えないという状況のようです。

## 検証

###  タイトルを英語にしたら太字になるか
```typst
= Introduction
```
<img width="433" alt="スクリーンショット 2024-09-12 15 39 36" src="https://github.com/user-attachments/assets/7b3f9fdd-03dc-46e3-bbe7-0d1852cded4b">

太字になる

### 本文中で強制的に太字にしたら太字になるか
```typst
このテンプレート *テンプレート* *template*
```
<img width="458" alt="スクリーンショット 2024-09-12 15 41 38" src="https://github.com/user-attachments/assets/a3f646fe-b141-4abc-a77d-68c1e164a99e">

日本語だと太字にならない

## 結論
違うフォントを採用しなきゃ。

**Comment by taiga4112** [comment]
typstの現時点でのバージョン(v0.11)では、日本語は太字にならない事象が複数確認されているようです。
[これ](https://github.com/kimushun1101/typst-jp-conf-template/blob/b6aa8da076ea9c1bf6ea6043574cd5c6e22ca205/main.typ#L182)とか、[これ](https://qiita.com/rockwell/items/280b4fd2109ef1e3c802)とか。

ということで、フォント設定をやり直し、太字に見えるフォントを採用することでごまかすことにしました。
